### ISSUE TITLE
Error while creating prediction

### ISSUE THREAD

**Issue by Borys520** [anasfik/replicate#4]
Hi, 
Thanks for the wonderful package! I am trying to create prediction but it always throws an error :

[Replicate] request started from/to: https://api.replicate.com/v1/predictions.
[Replicate] request from/to: https://api.replicate.com/v1/predictions end.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>'
#0      new Prediction.fromJson   prediction.dart:75
#1      ReplicatePrediction.create.<anonymous closure>   predictions.dart:62
#2      ReplicateHttpClient.post http_client.dart:54 <asynchronous suspension>
#3      _MyHomePageState.build.<anonymous closure> main.dart:61 <asynchronous suspension>

![image](https://github.com/anasfik/replicate/assets/84991764/52f50b01-3748-48d0-a850-b5987fe6d9f1)

**Comment by ZYLIM0702** [comment]
Hi, do you get the solution? Can you share with me? Thanks

**Comment by DavideSantoro** [comment]
I got the same error. Did you find a solution?

**Comment by alesspalma** [comment]
same error

**Comment by ZYLIM0702** [comment]
do you guys get the solution ? I still facing the same error

**Comment by DavideSantoro** [comment]
Hi, yes I found a solution. Let me go back at home and I'll send it to you.

Il mar 1 ago 2023, 14:48 ZYLIM0702 ***@***.***> ha scritto:

**Comment by ZYLIM0702** [comment]
Hi, if I don't use dotenv, then will it still be working ? And this is my code, can you provide me ways to debug my code ?
![IMG_20230802_001229.png](https://github.com/anasfik/replicate/assets/76156324/63201376-5066-4d57-9b3b-7c05574d1180)

**Comment by bigjjjim** [comment]
> await Future.delayed(Duration(seconds: 7));
>  PaginatedPredictions predictionsPageList =
>      await Replicate.instance.predictions.list();
> 
>  Prediction prediction = await Replicate.instance.predictions.get(
>    id: predictionsPageList.results.elementAt(0).id,
>  );
>  print(prediction.output);

Yes this way it works, but the object prediction does return null right after creating it. Even after 20 seconds, the object created by 
`Prediction prediction = await Replicate.instance.predictions.create()` returns null making it impossible to check with a stream or in a while loop... 
What if the model takes more than the 7 seconds? 

I suppose we could fetch the id from the list like you do then check the status but then my question is: 

Will the prediction be added to the list even thought it is not fully completed? And will it always take less than 7 seconds to be added to this list? 

Thank you for the code by the way, was really confused by this null prediction!
